---
title: "Extracting phenotype variable in UKB"
author: "Thi Thuy Dung Nguyen"
date: "12/3/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---
# INTRODUCTION
This document contains code to extract phenotype variables from UKB data accompanying the article:

Genetic heterogeneity and subtypes of major depression

Thuy-Dung Nguyen, M.Sc.(1,2); Arvid Harder, B.Sc.(1); Ying Xiong, M.Sc.(1); Kaarina Kowalec, Ph.D.(1,3); Sara Hägg, Ph.D.(1); Ralf Kuja-Halkola, Ph.D.(1); Christina Dalman, M.D.(2); Patrick F Sullivan, M.D. FRANZCP(1,4); Yi Lu, Ph.D.(1,2)

(1)	Department of Medical Epidemiology and Biostatistics, Karolinska Institutet, Stockholm, Sweden
(2)	Department of Global Public Health, Karolinska Institute, Stockholm, Sweden
(3)	College of Pharmacy, University of Manitoba, Winnipeg, Canada
(4)	Department of Genetics and Psychiatry, University of North Carolina, Chapel Hill, NC, USA

Corresponding author: 
Yi Lu, Ph.D.
Nobels Väg 12A, 
Solna, Sweden 17177  
lu.yi@ki.se 
Responsible for this code file
Thuy-Dung Nguyen
Nobels Väg 12A, 
Solna, Sweden 17177  
thuy.dung.nguyen@ki.se

Metadata about all variables can be found here
http://biobank.ctsu.ox.ac.uk/crystal/

The UKB phenotype data is stored in 2 original data files named ukb21472.tab (date 180427) and ukb22140.tab (date 180524). 

# Code template to extract variables
```{bash}
# Build a list for field names
var_list=(eid <put variables here>) # this var_list is changed corresponding to each small dataset extracted
index_array=()
for i in ${var_list[*]}
    do
        index_array+=($(head -1 /<path>/original_dataset.tab |tr -s "\t" "\n" | cat -n |grep -n $i |cut -d: -f1))
    done

# Buil a string from the index_array
index_str=" "
for i in ${index_array[*]}
    do
        index_str="${index_str}${i},"
    done
index_str=${index_str::-1}

# To check the index_string
echo "${index_str[*]}"

# Extract column using indexes (the cut option -f takes only string as argument)
cut -f $index_str /<path>/original_dataset.tab > /<path>/small_file_name.tab
```

# Variable list for child dataset
Below, we listed the original file name and the small dataset name together with variable list. Small dataset were mentioned in our code to derive variable, Derive_MD_case_control.Rmd and Derive_subtype.Rmd

## 1. Original dataset ukb21472.tab (date 180427) 
ukb180427_21472_p0.tab
var_list=(eid f.2090\. f.2100\. f.20126\. f.20002\. f.41202\. f.41204\.)

ukb180427_f20003.tab
var_list=(eid f.20003\.)

ukb180427_31.csv
var_list=(eid f.31\.)

ukb180427_2734.tab
var_list=(eid f.2734\.)

ukb180427_20126.tab
var_list=(eid f.20126\.)

## 2. Original dataset ukb22140.tab (date 180524)
ukb180524_20445_20544.tab
var_list=(eid f.20445\. f.20544\.)

ukb180524_20441_20446_20433.tab
var_list=(eid f.20441\. f.20446\. f.20433\.)

ukb180524_CIDI_criteria.tab
var_list=(eid f.20536\. f.20532\. f.20449\. f.20450\. f.20435\. f.20437\. f.20440\. f.20510\. f.20514\. f.20511\. f.20517\. f.20518\. f.20519\. f.20507\. f.20508\. f.20513\. f.20442\.)

ukb180524_20437_20447.tab
var_list=(eid f.20437\. f.20447\.)

ukb180524_20534.tab
var_list=(eid f.20534\.)



